/*
 * This file is generated by jOOQ.
 */
package com.hikarikun92.springsecurity.persistence.jooq.tables.records;


import com.hikarikun92.springsecurity.persistence.jooq.tables.UserCredentials;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCredentialsRecord extends UpdatableRecordImpl<UserCredentialsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1082750928;

    /**
     * Setter for <code>user_credentials.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_credentials.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user_credentials.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_credentials.password</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserCredentials.USER_CREDENTIALS.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UserCredentials.USER_CREDENTIALS.PASSWORD;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getPassword();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getPassword();
    }

    @Override
    public UserCredentialsRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserCredentialsRecord value2(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserCredentialsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserCredentialsRecord
     */
    public UserCredentialsRecord() {
        super(UserCredentials.USER_CREDENTIALS);
    }

    /**
     * Create a detached, initialised UserCredentialsRecord
     */
    public UserCredentialsRecord(Integer userId, String password) {
        super(UserCredentials.USER_CREDENTIALS);

        set(0, userId);
        set(1, password);
    }
}
