/*
 * This file is generated by jOOQ.
 */
package com.hikarikun92.springsecurity.persistence.jooq;


import com.hikarikun92.springsecurity.persistence.jooq.tables.User;
import com.hikarikun92.springsecurity.persistence.jooq.tables.UserCredentials;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_USERNAME_KEY = Indexes0.USER_USERNAME_KEY;
    public static final Index USER_CREDENTIALS_PKEY = Indexes0.USER_CREDENTIALS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_USERNAME_KEY = Internal.createIndex("user_username_key", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index USER_CREDENTIALS_PKEY = Internal.createIndex("user_credentials_pkey", UserCredentials.USER_CREDENTIALS, new OrderField[] { UserCredentials.USER_CREDENTIALS.USER_ID }, true);
    }
}
